// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WebUIClient is the client API for WebUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebUIClient interface {
	// ListEngineSpecs returns a list of Web Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (WebUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type webUIClient struct {
	cc grpc.ClientConnInterface
}

func NewWebUIClient(cc grpc.ClientConnInterface) WebUIClient {
	return &webUIClient{cc}
}

func (c *webUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (WebUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &WebUI_ServiceDesc.Streams[0], "/v1.WebUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &webUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WebUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type webUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *webUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.WebUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebUIServer is the server API for WebUI service.
// All implementations must embed UnimplementedWebUIServer
// for forward compatibility
type WebUIServer interface {
	// ListEngineSpecs returns a list of Web Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, WebUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedWebUIServer()
}

// UnimplementedWebUIServer must be embedded to have forward compatible implementations.
type UnimplementedWebUIServer struct {
}

func (UnimplementedWebUIServer) ListEngineSpecs(*ListEngineSpecsRequest, WebUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedWebUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedWebUIServer) mustEmbedUnimplementedWebUIServer() {}

// UnsafeWebUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebUIServer will
// result in compilation errors.
type UnsafeWebUIServer interface {
	mustEmbedUnimplementedWebUIServer()
}

func RegisterWebUIServer(s grpc.ServiceRegistrar, srv WebUIServer) {
	s.RegisterService(&WebUI_ServiceDesc, srv)
}

func _WebUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebUIServer).ListEngineSpecs(m, &webUIListEngineSpecsServer{stream})
}

type WebUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type webUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *webUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WebUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.WebUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebUI_ServiceDesc is the grpc.ServiceDesc for WebUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.WebUI",
	HandlerType: (*WebUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _WebUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _WebUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "web-ui.proto",
}
