package context

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

import (
	"github.com/bhojpur/web/pkg/context"
)

// BhojpurInput operates on the http request header, data, cookie and body.
// it also contains router params and current session.
type BhojpurInput context.BhojpurInput

// NewInput return BhojpurInput generated by Context.
func NewInput() *BhojpurInput {
	return (*BhojpurInput)(context.NewInput())
}

// Reset init the BhojpurInput
func (input *BhojpurInput) Reset(ctx *Context) {
	(*context.BhojpurInput)(input).Reset((*context.Context)(ctx))
}

// Protocol returns request protocol name, such as HTTP/1.1 .
func (input *BhojpurInput) Protocol() string {
	return (*context.BhojpurInput)(input).Protocol()
}

// URI returns full request url with query string, fragment.
func (input *BhojpurInput) URI() string {
	return input.Context.Request.RequestURI
}

// URL returns request url path (without query string, fragment).
func (input *BhojpurInput) URL() string {
	return (*context.BhojpurInput)(input).URL()
}

// Site returns base site url as scheme://domain type.
func (input *BhojpurInput) Site() string {
	return (*context.BhojpurInput)(input).Site()
}

// Scheme returns request scheme as "http" or "https".
func (input *BhojpurInput) Scheme() string {
	return (*context.BhojpurInput)(input).Scheme()
}

// Domain returns host name.
// Alias of Host method.
func (input *BhojpurInput) Domain() string {
	return (*context.BhojpurInput)(input).Domain()
}

// Host returns host name.
// if no host info in request, return localhost.
func (input *BhojpurInput) Host() string {
	return (*context.BhojpurInput)(input).Host()
}

// Method returns http request method.
func (input *BhojpurInput) Method() string {
	return (*context.BhojpurInput)(input).Method()
}

// Is returns boolean of this request is on given method, such as Is("POST").
func (input *BhojpurInput) Is(method string) bool {
	return (*context.BhojpurInput)(input).Is(method)
}

// IsGet Is this a GET method request?
func (input *BhojpurInput) IsGet() bool {
	return (*context.BhojpurInput)(input).IsGet()
}

// IsPost Is this a POST method request?
func (input *BhojpurInput) IsPost() bool {
	return (*context.BhojpurInput)(input).IsPost()
}

// IsHead Is this a Head method request?
func (input *BhojpurInput) IsHead() bool {
	return (*context.BhojpurInput)(input).IsHead()
}

// IsOptions Is this a OPTIONS method request?
func (input *BhojpurInput) IsOptions() bool {
	return (*context.BhojpurInput)(input).IsOptions()
}

// IsPut Is this a PUT method request?
func (input *BhojpurInput) IsPut() bool {
	return (*context.BhojpurInput)(input).IsPut()
}

// IsDelete Is this a DELETE method request?
func (input *BhojpurInput) IsDelete() bool {
	return (*context.BhojpurInput)(input).IsDelete()
}

// IsPatch Is this a PATCH method request?
func (input *BhojpurInput) IsPatch() bool {
	return (*context.BhojpurInput)(input).IsPatch()
}

// IsAjax returns boolean of this request is generated by ajax.
func (input *BhojpurInput) IsAjax() bool {
	return (*context.BhojpurInput)(input).IsAjax()
}

// IsSecure returns boolean of this request is in https.
func (input *BhojpurInput) IsSecure() bool {
	return (*context.BhojpurInput)(input).IsSecure()
}

// IsWebsocket returns boolean of this request is in webSocket.
func (input *BhojpurInput) IsWebsocket() bool {
	return (*context.BhojpurInput)(input).IsWebsocket()
}

// IsUpload returns boolean of whether file uploads in this request or not..
func (input *BhojpurInput) IsUpload() bool {
	return (*context.BhojpurInput)(input).IsUpload()
}

// AcceptsHTML Checks if request accepts html response
func (input *BhojpurInput) AcceptsHTML() bool {
	return (*context.BhojpurInput)(input).AcceptsHTML()
}

// AcceptsXML Checks if request accepts xml response
func (input *BhojpurInput) AcceptsXML() bool {
	return (*context.BhojpurInput)(input).AcceptsXML()
}

// AcceptsJSON Checks if request accepts json response
func (input *BhojpurInput) AcceptsJSON() bool {
	return (*context.BhojpurInput)(input).AcceptsJSON()
}

// AcceptsYAML Checks if request accepts json response
func (input *BhojpurInput) AcceptsYAML() bool {
	return (*context.BhojpurInput)(input).AcceptsYAML()
}

// IP returns request client ip.
// if in proxy, return first proxy id.
// if error, return RemoteAddr.
func (input *BhojpurInput) IP() string {
	return (*context.BhojpurInput)(input).IP()
}

// Proxy returns proxy client ips slice.
func (input *BhojpurInput) Proxy() []string {
	return (*context.BhojpurInput)(input).Proxy()
}

// Referer returns http referer header.
func (input *BhojpurInput) Referer() string {
	return (*context.BhojpurInput)(input).Referer()
}

// Refer returns http referer header.
func (input *BhojpurInput) Refer() string {
	return (*context.BhojpurInput)(input).Refer()
}

// SubDomains returns sub domain string.
// if aa.bb.domain.com, returns aa.bb .
func (input *BhojpurInput) SubDomains() string {
	return (*context.BhojpurInput)(input).SubDomains()
}

// Port returns request client port.
// when error or empty, return 80.
func (input *BhojpurInput) Port() int {
	return (*context.BhojpurInput)(input).Port()
}

// UserAgent returns request client user agent string.
func (input *BhojpurInput) UserAgent() string {
	return (*context.BhojpurInput)(input).UserAgent()
}

// ParamsLen return the length of the params
func (input *BhojpurInput) ParamsLen() int {
	return (*context.BhojpurInput)(input).ParamsLen()
}

// Param returns router param by a given key.
func (input *BhojpurInput) Param(key string) string {
	return (*context.BhojpurInput)(input).Param(key)
}

// Params returns the map[key]value.
func (input *BhojpurInput) Params() map[string]string {
	return (*context.BhojpurInput)(input).Params()
}

// SetParam will set the param with key and value
func (input *BhojpurInput) SetParam(key, val string) {
	(*context.BhojpurInput)(input).SetParam(key, val)
}

// ResetParams clears any of the input's Params
// This function is used to clear parameters so they may be reset between filter
// passes.
func (input *BhojpurInput) ResetParams() {
	(*context.BhojpurInput)(input).ResetParams()
}

// Query returns input data item string by a given string.
func (input *BhojpurInput) Query(key string) string {
	return (*context.BhojpurInput)(input).Query(key)
}

// Header returns request header item string by a given string.
// if non-existed, return empty string.
func (input *BhojpurInput) Header(key string) string {
	return (*context.BhojpurInput)(input).Header(key)
}

// Cookie returns request cookie item string by a given key.
// if non-existed, return empty string.
func (input *BhojpurInput) Cookie(key string) string {
	return (*context.BhojpurInput)(input).Cookie(key)
}

// Session returns current session item value by a given key.
// if non-existed, return nil.
func (input *BhojpurInput) Session(key interface{}) interface{} {
	return (*context.BhojpurInput)(input).Session(key)
}

// CopyBody returns the raw request body data as bytes.
func (input *BhojpurInput) CopyBody(MaxMemory int64) []byte {
	return (*context.BhojpurInput)(input).CopyBody(MaxMemory)
}

// Data return the implicit data in the input
func (input *BhojpurInput) Data() map[interface{}]interface{} {
	return (*context.BhojpurInput)(input).Data()
}

// GetData returns the stored data in this context.
func (input *BhojpurInput) GetData(key interface{}) interface{} {
	return (*context.BhojpurInput)(input).GetData(key)
}

// SetData stores data with given key in this context.
// This data are only available in this context.
func (input *BhojpurInput) SetData(key, val interface{}) {
	(*context.BhojpurInput)(input).SetData(key, val)
}

// ParseFormOrMulitForm parseForm or parseMultiForm based on Content-type
func (input *BhojpurInput) ParseFormOrMulitForm(maxMemory int64) error {
	return (*context.BhojpurInput)(input).ParseFormOrMultiForm(maxMemory)
}

// Bind data from request.Form[key] to dest
// like /?id=123&isok=true&ft=1.2&ol[0]=1&ol[1]=2&ul[]=str&ul[]=array&user.Name=bhojpur
// var id int  bhojpurInput.Bind(&id, "id")  id ==123
// var isok bool  bhojpurInput.Bind(&isok, "isok")  isok ==true
// var ft float64  bhojpurInput.Bind(&ft, "ft")  ft ==1.2
// ol := make([]int, 0, 2)  bhojpurInput.Bind(&ol, "ol")  ol ==[1 2]
// ul := make([]string, 0, 2)  bhojpurInput.Bind(&ul, "ul")  ul ==[str array]
// user struct{Name}  bhojpurInput.Bind(&user, "user")  user == {Name:"bhojpur"}
func (input *BhojpurInput) Bind(dest interface{}, key string) error {
	return (*context.BhojpurInput)(input).Bind(dest, key)
}
